version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: znap-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: znap
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: znap-backend
    restart: always
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: znap
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: znap-frontend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - backend

volumes:
  db_data:
